# Generated by Django 4.0.8 on 2024-06-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_like_post_remove_like_user_remove_post_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='short_name',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
